# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Econ5170
# email: zhentao.shi@cuhk.edu.hk
name: Teaching
description: > # this means to ignore newlines until "baseurl:"
  Webpage
baseurl: "/econ5170" # the subpath of your site, e.g. /blog
url: "http://zhentaoshi.github.io" # the base hostname & protocol for your site
# theme: minima
twitter_username: n/a
github_username:  zhentaoshi

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
